# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrailBlazer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrailBlazer
  pod 'GoogleMaps'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'TrailBlazerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrailBlazerUITests' do
    # Pods for testing
  end

end
